name: Housekeeping - Dry run
on:
    push:
      branches:
        - '*'
        - '!master'
    pull_request:
      branches: [master]
jobs:
  daily_update:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
       with:
         node-version: 12
     - name: Install Dependencies
       run: npm ci
     - name: Run update script
       run: npm run new-housekeeping
     - name: Run test
       run: npm t
